"""Time the JAX EFGP path and compare against the torch baseline.

Reads tests/_torch_timing.json (generated by _time_torch_path.py).  Prints
a side-by-side table; only fails if JAX is >10x slower (i.e. an obvious
performance regression rather than the expected ~equal cost).
"""
from __future__ import annotations

import json
import math
import sys
import time
from pathlib import Path

import numpy as np
import pytest

_HERE = Path(__file__).resolve().parent
_SING = _HERE.parent
if str(_SING) not in sys.path:
    sys.path.insert(0, str(_SING))

# load jax_finufft FIRST via this module
import sing.efgp_jax_primitives as jp
import jax
import jax.numpy as jnp
import jax.random as jr

TORCH_TIMING = _HERE / "_torch_timing.json"


def _time_jax_step(d: int, N: int, ls: float, var: float, eps_grid: float,
                    n_warmup: int = 2, n_iters: int = 10):
    rng = np.random.default_rng(0)
    X_np = rng.standard_normal((N, d)).astype(np.float32)
    weights_np = rng.uniform(0.5, 1.5, size=N).astype(np.float32)
    X = jnp.asarray(X_np)
    W = jnp.asarray(weights_np)
    grid = jp.spectral_grid_se(ls, var, X, eps=eps_grid)

    @jax.jit
    def step(W, y):
        v_kernel = jp.bttb_conv_vec_weighted(X, W, grid.xcen, grid.h_per_dim,
                                              grid.mtot_per_dim)
        top = jp.make_toeplitz(v_kernel, force_pow2=True)
        A = jp.make_A_apply(grid.ws, top, sigmasq=1.0)
        # h_r = D F* (W * y)
        Wy = W.astype(jnp.complex64) * y
        h_r = grid.ws.real.astype(jnp.complex64) * jp.nufft1(
            X, Wy, grid.xcen, grid.h_per_dim,
            out_shape=grid.mtot_per_dim, eps=6e-8).reshape(-1)
        return jp.cg_solve(A, h_r, tol=1e-5, max_iter=4 * grid.M)

    y0 = jnp.asarray(np.random.default_rng(1).standard_normal(N), dtype=jnp.complex64)
    # warmup (compile)
    for _ in range(n_warmup):
        out = step(W, y0); out.block_until_ready()
    t0 = time.time()
    for k in range(n_iters):
        y = jnp.asarray(np.random.default_rng(k + 100).standard_normal(N),
                        dtype=jnp.complex64)
        out = step(W, y); out.block_until_ready()
    dt = (time.time() - t0) / n_iters
    return {'M': int(grid.M), 'ms_per_iter': dt * 1000.0}


@pytest.mark.skipif(not TORCH_TIMING.exists(),
                     reason="run python tests/_time_torch_path.py first")
def test_jax_timing_within_10x_torch():
    torch_times = json.loads(TORCH_TIMING.read_text())
    print("\n  config                                    M   torch  jax    ratio")
    print("  " + "-" * 72)
    worst_ratio = 0.0
    for cfg, torch_res in torch_times.items():
        # parse cfg
        parts = dict(p.split("=") for p in cfg.split(","))
        ls = float(parts['ls']); eps_grid = float(parts['eps'])
        N = int(parts['N']); d = int(parts['d'])
        jax_res = _time_jax_step(d=d, N=N, ls=ls, var=1.0,
                                  eps_grid=eps_grid, n_iters=20)
        ratio = jax_res['ms_per_iter'] / torch_res['ms_per_iter']
        worst_ratio = max(worst_ratio, ratio)
        print(f"  {cfg:40s} {jax_res['M']:5d} {torch_res['ms_per_iter']:6.2f} "
              f"{jax_res['ms_per_iter']:6.2f} {ratio:6.2f}x")
    # informational; only fail if JAX is dramatically slower
    assert worst_ratio < 10.0, (
        f"JAX is {worst_ratio:.2f}x slower than torch on the worst config — "
        f"investigate before continuing")
