"""
Parity tests for the JAX EFGP primitives in sing.efgp_jax_primitives.

Reference values come from a torch + efgpnd run, generated by
``tests/_make_torch_reference.py`` (in a separate process — torch's
``pytorch_finufft`` and ``jax_finufft`` segfault if both are loaded
sequentially).  Run that script once before this test file:

    python tests/_make_torch_reference.py

Then run with:

    pytest tests/test_efgp_jax_primitives.py -v
"""
from __future__ import annotations

import pickle
import sys
from pathlib import Path

import numpy as np
import pytest

# Make sing/ importable
_HERE = Path(__file__).resolve().parent
_SING = _HERE.parent
if str(_SING) not in sys.path:
    sys.path.insert(0, str(_SING))

# Import jax_finufft FIRST via the JAX-primitives module (load-order constraint)
import sing.efgp_jax_primitives as jp
import jax
import jax.numpy as jnp

REF_PATH = _HERE / "_torch_reference.pkl"

# JAX defaults to float32; tighter tolerances are unrealistic without enabling
# x64 globally (which TFP doesn't support in the SING jax 0.6 pin).
TOL = 1e-5


@pytest.fixture(scope="module")
def ref():
    if not REF_PATH.exists():
        pytest.skip(
            f"Run python tests/_make_torch_reference.py first to generate "
            f"{REF_PATH}")
    return pickle.loads(REF_PATH.read_bytes())


# ---------------------------------------------------------------------------
def _rel(a, b):
    return float(np.linalg.norm(np.asarray(a) - np.asarray(b))
                 / (np.linalg.norm(b) + 1e-30))


# ---------------------------------------------------------------------------
def test_spectral_grid_matches_torch(ref):
    cfg = ref['config']
    X = jnp.asarray(ref['X'], dtype=jnp.float32)
    grid = jp.spectral_grid_se(cfg['ls'], cfg['var'], X, eps=cfg['eps_grid'])
    assert grid.M == ref['M'], f"M differs: jax {grid.M} vs torch {ref['M']}"
    assert tuple(grid.mtot_per_dim) == tuple(ref['mtot_per_dim'])
    assert _rel(grid.h_per_dim, ref['h_per_dim']) < TOL
    assert _rel(grid.xis_flat, ref['xis_flat']) < TOL
    # ws is complex; magnitudes are what we care about
    assert _rel(np.abs(np.asarray(grid.ws)), np.abs(ref['ws'])) < TOL
    assert _rel(grid.xcen, ref['xcen']) < TOL


def test_nufft1_matches_torch(ref):
    X = jnp.asarray(ref['X'], dtype=jnp.float32)
    h_per_dim = jnp.asarray(ref['h_per_dim'], dtype=jnp.float32)
    xcen = jnp.asarray(ref['xcen'], dtype=jnp.float32)
    vals = jnp.asarray(ref['vals_cplx'], dtype=jnp.complex64)
    out = jp.nufft1(X, vals, xcen, h_per_dim,
                    out_shape=tuple(ref['mtot_per_dim']), eps=6e-8)
    assert _rel(out, ref['out_nufft1']) < TOL


def test_nufft2_matches_torch(ref):
    X = jnp.asarray(ref['X'], dtype=jnp.float32)
    h_per_dim = jnp.asarray(ref['h_per_dim'], dtype=jnp.float32)
    xcen = jnp.asarray(ref['xcen'], dtype=jnp.float32)
    fk = jnp.asarray(ref['fk_grid'], dtype=jnp.complex64)
    out = jp.nufft2(X, fk, xcen, h_per_dim, eps=6e-8)
    assert _rel(out, ref['out_nufft2']) < TOL


def test_bttb_conv_vec_weighted_matches_torch(ref):
    X = jnp.asarray(ref['X'], dtype=jnp.float32)
    W = jnp.asarray(ref['weights'], dtype=jnp.float32)
    h_per_dim = jnp.asarray(ref['h_per_dim'], dtype=jnp.float32)
    xcen = jnp.asarray(ref['xcen'], dtype=jnp.float32)
    v_kernel = jp.bttb_conv_vec_weighted(X, W, xcen, h_per_dim,
                                          tuple(ref['mtot_per_dim']),
                                          eps=6e-8)
    assert _rel(v_kernel, ref['v_kernel']) < TOL


def test_toeplitz_apply_matches_torch(ref):
    v_kernel = jnp.asarray(ref['v_kernel'])  # already complex
    top = jp.make_toeplitz(v_kernel, force_pow2=True)
    test_vec = jnp.asarray(ref['test_vec'], dtype=jnp.complex64)
    out = jp.toeplitz_apply(top, test_vec)
    assert _rel(out, ref['out_toeplitz']) < TOL


def test_A_apply_matches_torch(ref):
    v_kernel = jnp.asarray(ref['v_kernel'])
    top = jp.make_toeplitz(v_kernel, force_pow2=True)
    ws = jnp.asarray(ref['ws'])
    A = jp.make_A_apply(ws, top, sigmasq=1.0)
    test_vec = jnp.asarray(ref['test_vec'], dtype=jnp.complex64)
    out = A(test_vec)
    assert _rel(out, ref['out_Aapply']) < TOL


def test_cg_solve_matches_torch(ref):
    v_kernel = jnp.asarray(ref['v_kernel'])
    top = jp.make_toeplitz(v_kernel, force_pow2=True)
    ws = jnp.asarray(ref['ws'])
    A = jp.make_A_apply(ws, top, sigmasq=1.0)
    h_r = jnp.asarray(ref['h_r'], dtype=jnp.complex64)
    mu = jp.cg_solve(A, h_r, tol=1e-8, max_iter=4 * ref['M'])
    # CG agreement to a slightly looser tol — both solvers can converge to
    # different points within their own tolerances.
    rel = _rel(mu, ref['mu_solve'])
    assert rel < 1e-3, f"CG μ rel error {rel:.2e}"


def test_hutchinson_diag_consistent(ref):
    """Hutchinson is unbiased; with enough probes the mean should agree
    with a dense reference.  We compute the dense reference here in NumPy
    (small problem so cheap), then call the JAX estimator."""
    import math
    X = ref['X']
    weights = ref['weights']
    ws = ref['ws']
    xis = ref['xis_flat']
    xcen = ref['xcen']

    # Dense Φ_eval at the training points  Φ[n,k] = exp(2πi ξ_k · (x_n - xcen))
    F = np.exp(1j * 2 * math.pi * (X - xcen) @ xis.T)              # (N, M)
    D = np.diag(ws)                                                 # (M, M)
    W = np.diag(weights.astype(np.complex128))                      # (N, N)
    A_dense = np.eye(len(ws), dtype=np.complex128) + D @ F.conj().T @ W @ F @ D
    A_inv = np.linalg.inv(A_dense)
    var_dense = np.real(np.einsum('nk,kl,nl->n', F, D @ A_inv @ D, F.conj()))

    # JAX side
    v_kernel = jnp.asarray(ref['v_kernel'])
    top = jp.make_toeplitz(v_kernel, force_pow2=True)
    ws_j = jnp.asarray(ws)
    A = jp.make_A_apply(ws_j, top, sigmasq=1.0)

    grid = jp.JaxGridState(
        xis_flat=jnp.asarray(xis, dtype=jnp.float32),
        ws=ws_j,
        h_per_dim=jnp.asarray(ref['h_per_dim'], dtype=jnp.float32),
        mtot_per_dim=tuple(ref['mtot_per_dim']),
        xcen=jnp.asarray(xcen, dtype=jnp.float32),
        M=int(ref['M']), d=int(ref['X'].shape[1]),
    )
    X_eval_j = jnp.asarray(X, dtype=jnp.float32)
    var_hutch = jp.hutchinson_diag(grid, top, X_eval_j, A,
                                    key=jax.random.PRNGKey(123),
                                    J=1024, cg_tol=1e-6,
                                    max_cg_iter=4 * ref['M'])
    err = np.abs(np.asarray(var_hutch) - var_dense)
    typical = np.median(np.abs(var_dense)) + 1e-12
    mean_rel = err.mean() / typical
    assert mean_rel < 0.10, f"Hutchinson mean rel err {mean_rel:.3f}"
